version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_HOST: mariadb
    container_name: wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - wordpress_sessions:/var/www/html/wp-content/uploads 
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  wordpress_sessions:






