version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/home/${USER}/data/
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_HOST: mariadb
    container_name: wordpress
    volumes:
      - wordpress_data:/home/${USER}/data/
      - wordpress_sessions:/home/${USER}/data/
    networks:
      - wordpress_network

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - wordpress_network
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always


networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  wordpress_sessions:
 






