version: "3,5"

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver-opts:
      type: none
      o: bind
      device: /home/emencova/data/wordpress

  mariadb:
    driver: local
    name: mariadb
    driver-opts:
      type: none
      o: bind
      device: /home/emencova/mariadb

services:
  maria_db:
    container_name: maria_db
    build: ./mariadb/.
    env-file:
      - .env
    volumes:
      - mariadb: /var/lib/mysql
    networks:
      my-network
    restart:
      unless-stopped

  word_press:
    container_name: word_press
    build: ./wordpress/.
    env-file:
      - .env
    volumes:
      - wordpress: /var/www/html
    networks:
      my-network
    restart:
      unless-stopped


  Nginx:
    container_name: Nginx
    build: ./ngintx/.
    ports:
      -"443:443"
    depends_on:
      -word_press
    volumes:
      - wordpress: /var/www/html
    networks:
      - my-network
    restart:
      unless-stopped


